# Generated by Django 5.2.5 on 2025-08-19 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='image',
            new_name='image_url',
        ),
    ]
