# Generated by Django 5.2.5 on 2025-08-19 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_rename_image_doctor_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='image_url',
            new_name='image',
        ),
    ]
